version: '3.8'

services:
  # MongoDB
  mongo:
    image: mongo:latest
    container_name: managify-mongo
    environment:
      MONGO_INITDB_DATABASE: managify
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


volumes:
  mongo_data: