version: "3.9"

services:
  backend:
    container_name: managify-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - GO_ENV=production
    restart: unless-stopped
    networks:
      - managify-net

networks:
  managify-net:
    driver: bridge
